# -*- coding: utf-8 -*-
"""wholesale_data_analysis_starter_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbeHBoHvreSnmbIK_An4X3pRFd5XUFtP

## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.
"""

import pandas as pd

df = pd.read_csv('/content/client_dataset.csv')
df.head()

# View the column names in the data
df.columns

# Use the describe function to gather some basic statistics
df.describe()

# Use this space to do any additional research
# and familiarize yourself with the data.
df.info()

# What three item categories had the most entries?
df['category'].value_counts().head(3)

# For the category with the most entries, which subcategory had the most entries?
df.loc[df['category'] == 'consumables', 'subcategory'].value_counts().head(1)

# Which five clients had the most entries in the data?
df['client_id'].value_counts().head(5)

# Store the client ids of those top 5 clients in a list.
top_5_clients = list(df['client_id'].value_counts().head(5).index)
top_5_clients

# How many total units (the qty column) did the client with the most entries order order?
df.loc[df['client_id'] == 33615, 'qty'].sum()

"""## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.
"""

# Create a column that calculates the subtotal for each line using the unit_price and the qty
df['subtotal'] = df['unit_price'] * df['qty']
df[['unit_price', 'qty', 'subtotal']].head(2)

# Create a column for shipping price.
# Assume a shipping price of $7 per pound for orders over 50 pounds and $10 per pound for items 50 pounds or under.
def calculator(weight):
    if weight > 50:
        return weight * 7
    return weight * 10

df['weight'] = df['qty'] * df['unit_weight']
df['shipping_cost'] = df['weight'].apply(calculator)
df[['unit_price', 'unit_weight', 'qty', 'weight', 'shipping_cost']].head(3)

# Create a column for the total price using the subtotal and the shipping price along with a sales tax of 9.25%
df['line_price'] = round((df['subtotal'] + df['shipping_cost']) * 1.0925, 2)
df[['subtotal', 'shipping_cost', 'line_price']].head(3)

# Create a column for the cost of each line using unit cost, qty, and
# shipping price (assume the shipping cost is exactly what is charged to the client).
df['line_cost'] = df['unit_cost'] * df['qty'] + df['shipping_cost']
df.head()

# Create a column for the profit of each line using line cost and line price
df['line_profit'] = df['line_price'] - df['line_cost']
df.head()

"""## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25

"""

# Check your work using the totals above
order_ids = [8953482, 8069089, 1902144]

def show_order_price(order_id):
    order_df = df.loc[df['order_id'] == order_id, 'line_price']
    return round(order_df.sum(), 4)

for order_id in order_ids:
    print(f"Order {order_id} total: ${show_order_price(order_id)}")

"""## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.
"""

# How much did each of the top 5 clients by quantity spend? Check your work from Part 1 for client ids.
def client_totals(client_id, column):
    client_df = df.loc[df['client_id'] == client_id, column]
    return round(client_df.sum(), 2)

for client_id in top_5_clients:
    print(f"{client_id}: ${client_totals(client_id, 'line_price')}")

# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit.
data_dictionary = {'client_id': top_5_clients}
columns = ['qty', 'shipping_cost', 'line_price', 'line_cost', 'line_profit']
for col in columns:
    data_dictionary[col] = [client_totals(client_id, col) for client_id in top_5_clients]

summary_df = pd.DataFrame(data_dictionary)
summary_df

# Format the data and rename the columns to names suitable for presentation.

# Define the money columns.
money_columns = ['line_price', 'shipping_cost', 'line_cost', 'line_profit']

# Define a function that converts a dollar amount to millions.
def currency_format_millions(amount):
    return amount/1000000

# Apply the currency_format_millions function to only the money columns.
for col in money_columns:
    summary_df[col] = summary_df[col].apply(currency_format_millions)

# Rename the columns to reflect the change in the money format.
rename_dictionary_millions = {
    'client_id': 'Client ID',
    'line_price': 'Total Revenue (millions)',
    'shipping_cost': 'Shipping (millions)',
    'qty': 'Units',
    'line_cost': 'Total Cost (millions)',
    'line_profit': 'Total Profit (millions)'
}
summary_df = summary_df.rename(columns = rename_dictionary_millions)
summary_df

# Sort the updated data by "Total Profit (millions)" form highest to lowest and assign the sort to a new DatFrame.
sort_order_df = summary_df.sort_values('Total Profit (millions)', ascending=False)
sort_order_df

